name: SONAR
on:
  push:
    branches: [ main ]
    paths: [ 'pom.xml', 'src/**', '.github/workflows/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'pom.xml', 'src/**', '.github/workflows/**' ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-analyze:
    name: "Build, Test, Analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build & Test (with coverage)
        run: mvn -B -DskipTests=false test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload JaCoCo HTML (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-site
          path: target/site/jacoco

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # explicit params if auto-detect fails:
          # projectKey: your_org_your_project
          # organization: your_org
          args: >
             -Dsonar.projectKey=ludens2038_cicd-kekic-01
             -Dsonar.organization=ludens2038
             -Dsonar.branch.name=main  
             -Dsonar.java.binaries=target/classes
             -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml